# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieBase', '0002_auto_20170828_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role', to='MovieBase.Person'),
        ),
    ]
